<a href="https://colab.research.google.com/github/kartoch/colab-eda/blob/master/01%20-%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sheet 1: Numpy

## Python

In [0]:
a=3

In [0]:
a

3

In [0]:
a=5

In [0]:
a

5

## Jupyter 
**azpodkazpokdpoazazdp** ojdzapda *uidhazidaz* 
# un titre
## un sous-titre
[http://www.google.fr](un lien vers google)

## Numpy BS Python

In [0]:
def my_funct():
    """ 
    c'est la méthode A
    """
    x = 0
    y = []
    # je commence la boucle
    for i in range(1000):
        y.append(i)
    for i in y:
        x += i
    return x

In [0]:
%time my_funct()

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 265 µs


499500

In [0]:
%timeit my_funct()

107 µs ± 3.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [0]:
import numpy as np

In [0]:
%timeit np.arange(1000).sum()

3.99 µs ± 303 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Create numpy array and matrix

In [0]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [0]:
np.zeros(5,dtype=np.int64)

array([0, 0, 0, 0, 0])

In [0]:
np.zeros(5,dtype=np.int8)

array([0, 0, 0, 0, 0], dtype=int8)

In [0]:
b = np.arange(20, dtype=np.int16)

In [0]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int16)

In [0]:
b.shape

(20,)

In [0]:
len(b)

20

In [0]:
b.size

20

In [0]:
b.ndim

1

In [0]:
b.dtype

dtype('int16')

In [0]:
b.strides

(2,)

In [0]:
c = np.arange(27).reshape((3,3,3))

In [0]:
c.strides

(72, 24, 8)

## Access

In [0]:
c[2] = -5

In [0]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[-5, -5, -5],
        [-5, -5, -5],
        [-5, -5, -5]]])

In [0]:
c[2,1] = - 7

In [0]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[-5, -5, -5],
        [-7, -7, -7],
        [-5, -5, -5]]])

In [0]:
c[0,0,1] = - 10

In [0]:
c

array([[[  0, -10,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ -5,  -5,  -5],
        [ -7,  -7,  -7],
        [ -5,  -5,  -5]]])

## Access with ::

In [0]:
e = np.arange(10)
e[3::]

array([3, 4, 5, 6, 7, 8, 9])

In [0]:
e[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [0]:
e[:7:]

array([0, 1, 2, 3, 4, 5, 6])

In [0]:
e[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [0]:
e[::2]

array([0, 2, 4, 6, 8])

In [0]:
e[-3::]

array([7, 8, 9])

## Access with boolean array

In [0]:
g = np.random.randint(0,2,64)
g[g == 1] = 3
g

array([0, 3, 3, 0, 0, 3, 3, 3, 0, 3, 3, 3, 0, 3, 0, 3, 0, 0, 3, 3, 3, 0, 3,
       3, 0, 0, 0, 3, 0, 0, 0, 3, 3, 3, 0, 0, 3, 0, 3, 3, 3, 3, 0, 3, 3, 0,
       3, 0, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 3, 0, 3, 3])

In [0]:
h1 = np.array([False,True],dtype=np.bool)
h2 = np.array([True,True],dtype=np.bool)
h1 & h2

array([False,  True], dtype=bool)

In [0]:
np.array([0,2,3]).any()

True

In [0]:
np.array([0,0]).any()

False

## Matrix operations

In [0]:
np.arange(4).reshape(2,2) + np.ones((2,2))

array([[ 1.,  2.],
       [ 3.,  4.]])

In [0]:
np.arange(4).reshape(2,2) + np.ones((2))

array([[ 1.,  2.],
       [ 3.,  4.]])

In [0]:
np.arange(4).reshape(2,2) * np.arange(4).reshape(2,2)

array([[0, 1],
       [4, 9]])

In [0]:
np.arange(4).reshape(2,2).dot(np.arange(4).reshape(2,2))

array([[ 2,  3],
       [ 6, 11]])

In [0]:
np.arange(4).reshape(2,2) * np.arange(2).reshape(1,2)

array([[0, 1],
       [0, 3]])

In [0]:
np.arange(4).reshape(2,2) * np.arange(2).reshape(2,1)

array([[0, 0],
       [2, 3]])

## Access via axis

In [0]:
np.arange(25).reshape(5,5).sum()

300

In [0]:
np.arange(25).reshape(5,5).sum(axis=0)

array([50, 55, 60, 65, 70])

In [0]:
np.arange(25).reshape(5,5).sum(axis=1)

array([ 10,  35,  60,  85, 110])

## Access via sublists

In [0]:
np.arange(25).reshape(5,5)[[2,4]]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Questions

**Q:** Create a null vector of size 10 but the fifth value which is 1

**Q:** Reverse a vector (first element becomes last) 

**Q:** Create a 10x10 array with random values and find the minimum and maximum values 

**Q:** Create a 10x10 array with random values and find the minimum and maximum values of each sub-matrix

**Q:** Create a 2d array with 1 on the border and 0 inside

**Q:** Create a 8x8 matrix and fill it with a checkerboard pattern

**Q:** Create a 8x8 matrix and fill it with a checkerboard pattern using [tile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html)

**Q:** Given a 1D array, negate all elements which are between 3 and 8, in place

**Q:** Create a 5x5 matrix with row values ranging from 0 to 4

**Q:** Subtract the mean of each row of a random matrix

**Q:** How to find the most frequent value in an array?

**Q:** How to swap the second and the third rows of an 5x5 random matrix ?

**Q:** How to tell if a given 2D array has null columns?