<a href="https://colab.research.google.com/github/kartoch/colab-eda/blob/master/02%20-%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [0]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [0]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [0]:
data.values

array([ 0.25,  0.5 ,  0.75,  1.  ])

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])

In [0]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [0]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [0]:
data['b']

0.5

In [0]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)

In [0]:
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [0]:
population.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [0]:
population.values

array([38332521, 19552860, 12882135, 19651127, 26448193])

In [0]:
population['California':'Illinois']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

In [0]:
area_dict = {'California': 423967, 
             'Texas': 695662, 
             'New York': 141297,
             'Florida': 170312, 
             'Illinois': 149995}
area = pd.Series(area_dict)

In [0]:
area_dict

{'California': 423967,
 'Florida': 170312,
 'Illinois': 149995,
 'New York': 141297,
 'Texas': 695662}

In [0]:
population_dict

{'California': 38332521,
 'Florida': 19552860,
 'Illinois': 12882135,
 'New York': 19651127,
 'Texas': 26448193}

In [0]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [0]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [0]:
states.columns

Index(['area', 'population'], dtype='object')

In [0]:
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [0]:
states['area'].values

array([423967, 170312, 149995, 141297, 695662])

In [0]:
states.loc['California']

area            423967
population    38332521
Name: California, dtype: int64

In [0]:
states.loc['California':'Florida']

area  population
California  423967    38332521
Florida     170312    19552860

In [0]:
states['density'] = states['population'] / states['area']

In [0]:
states

area  population     density
California  423967    38332521   90.413926
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763
New York    141297    19651127  139.076746
Texas       695662    26448193   38.018740

In [0]:
states.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, California to Texas
Data columns (total 3 columns):
area          5 non-null int64
population    5 non-null int64
density       5 non-null float64
dtypes: float64(1), int64(2)
memory usage: 320.0+ bytes


In [0]:
states['density']

California     90.413926
Florida       114.806121
Illinois       85.883763
New York      139.076746
Texas          38.018740
Name: density, dtype: float64

In [0]:
states.iloc[2,2]

85.883762792093066

In [0]:
states.loc["Illinois",'density']

85.883762792093066

In [0]:
states.T

California       Florida      Illinois      New York  \
area        4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05   
population  3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07   
density     9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02   

                   Texas  
area        6.956620e+05  
population  2.644819e+07  
density     3.801874e+01

In [0]:
states.loc['California':'Illinois','area':'population']

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135

In [0]:
states.loc['California':'Illinois',['density','area']]

density    area
California   90.413926  423967
Florida     114.806121  170312
Illinois     85.883763  149995

In [0]:
states['density'] > 90

California     True
Florida        True
Illinois      False
New York       True
Texas         False
Name: density, dtype: bool

In [0]:
states[states['density'] > 90]

area  population     density
California  423967    38332521   90.413926
Florida     170312    19552860  114.806121
New York    141297    19651127  139.076746

In [0]:
states[(states['density'] > 90) &\
       (states['population']<20000000)]

area  population     density
Florida   170312    19552860  114.806121
New York  141297    19651127  139.076746

In [0]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

In [0]:
multi_index = pd.MultiIndex.from_tuples(index)
multi_index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [0]:
pop = pd.DataFrame({'population': populations},
                   index=multi_index)
pop

population
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [0]:
pop.loc['California',2010]

population    37253956
Name: (California, 2010), dtype: int64

In [0]:
pop.unstack()

population          
                 2000      2010
California   33871648  37253956
New York     18976457  19378102
Texas        20851820  25145561